In [1]:
import pandas as pd

file_path = "../data/raw/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"

df = pd.read_csv(file_path)

print(df.shape)
df.head()

(225745, 79)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 225745 entries, 0 to 225744
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             225745 non-null  int64
 1    Flow Duration                225745 non-null  int64
 2    Total Fwd Packets            225745 non-null  int64
 3    Total Backward Packets       225745 non-null  int64
 4   Total Length of Fwd Packets   225745 non-null  int64
 5    Total Length of Bwd Packets  225745 non-null  int64
 6    Fwd Packet Length Max        225745 non-null  int64
 7    Fwd Packet Length Min        225745 non-null  int64
 8    Fwd Packet Length Mean       225745 non-null  float64
 9    Fwd Packet Length Std        225745 non-null  float64
 10  Bwd Packet Length Max         225745 non-null  int64
 11   Bwd Packet Length Min        225745 non-null  int64
 12   Bwd Packet Length Mean       225745 non-null  float64
 13   Bwd Packet Length Std        225745 non-null  float64
 14  Flow Bytes/s                  225741 non-null  float64
 15   Flow Packets/s               225745 non-null  float64
 16   Flow IAT Mean                225745 non-null  float64
 17   Flow IAT Std                 225745 non-null  float64
 18   Flow IAT Max                 225745 non-null  int64
 19   Flow IAT Min                 225745 non-null  int64
 20  Fwd IAT Total                 225745 non-null  int64
 21   Fwd IAT Mean                 225745 non-null  float64
 22   Fwd IAT Std                  225745 non-null  float64
 23   Fwd IAT Max                  225745 non-null  int64
 24   Fwd IAT Min                  225745 non-null  int64
 25  Bwd IAT Total                 225745 non-null  int64
 26   Bwd IAT Mean                 225745 non-null  float64
 27   Bwd IAT Std                  225745 non-null  float64
 28   Bwd IAT Max                  225745 non-null  int64
 29   Bwd IAT Min                  225745 non-null  int64
 30  Fwd PSH Flags                 225745 non-null  int64
 31   Bwd PSH Flags                225745 non-null  int64
 32   Fwd URG Flags                225745 non-null  int64
 33   Bwd URG Flags                225745 non-null  int64
 34   Fwd Header Length            225745 non-null  int64
 35   Bwd Header Length            225745 non-null  int64
 36  Fwd Packets/s                 225745 non-null  float64
 37   Bwd Packets/s                225745 non-null  float64
 38   Min Packet Length            225745 non-null  int64
 39   Max Packet Length            225745 non-null  int64
 40   Packet Length Mean           225745 non-null  float64
 41   Packet Length Std            225745 non-null  float64
 42   Packet Length Variance       225745 non-null  float64
 43  FIN Flag Count                225745 non-null  int64
 44   SYN Flag Count               225745 non-null  int64
 45   RST Flag Count               225745 non-null  int64
 46   PSH Flag Count               225745 non-null  int64
 47   ACK Flag Count               225745 non-null  int64
 48   URG Flag Count               225745 non-null  int64
 49   CWE Flag Count               225745 non-null  int64
 50   ECE Flag Count               225745 non-null  int64
 51   Down/Up Ratio                225745 non-null  int64
 52   Average Packet Size          225745 non-null  float64
 53   Avg Fwd Segment Size         225745 non-null  float64
 54   Avg Bwd Segment Size         225745 non-null  float64
 55   Fwd Header Length.1          225745 non-null  int64
 56  Fwd Avg Bytes/Bulk            225745 non-null  int64
 57   Fwd Avg Packets/Bulk         225745 non-null  int64
 58   Fwd Avg Bulk Rate            225745 non-null  int64
 59   Bwd Avg Bytes/Bulk           225745 non-null  int64
 60   Bwd Avg Packets/Bulk         225745 non-null  int64
 61  Bwd Avg Bulk Rate             225745 non-null  int64
 62  Subflow Fwd Packets           225745 non-null  int64
 63   Subflow Fwd Bytes            225745 non-null  int64
 64   Subflow Bwd Packets          225745 non-null  int64
 65   Subflow Bwd Bytes            225745 non-null  int64
 66  Init_Win_bytes_forward        225745 non-null  int64
 67   Init_Win_bytes_backward      225745 non-null  int64
 68   act_data_pkt_fwd             225745 non-null  int64
 69   min_seg_size_forward         225745 non-null  int64
 70  Active Mean                   225745 non-null  float64
 71   Active Std                   225745 non-null  float64
 72   Active Max                   225745 non-null  int64
 73   Active Min                   225745 non-null  int64
 74  Idle Mean                     225745 non-null  float64
 75   Idle Std                     225745 non-null  float64
 76   Idle Max                     225745 non-null  int64
 77   Idle Min                     225745 non-null  int64
 78   Label                        225745 non-null  str
dtypes: float64(24), int64(54), str(1)
memory usage: 136.1 MB

In [3]:
df.describe()

c:\Projects\CyberSentinel-AI\venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Projects\CyberSentinel-AI\venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,225745.00000,2.257450e+05,225745.000000,225745.000000,225745.000000,2.257450e+05,225745.000000,225745.000000,225745.000000,225745.000000,...,225745.000000,225745.000000,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05
mean,8879.61946,1.624165e+07,4.874916,4.572775,939.463346,5.960477e+03,538.535693,27.882221,164.826715,214.907242,...,3.311497,21.482753,1.848261e+05,1.293436e+04,2.080849e+05,1.776201e+05,1.032214e+07,3.611943e+06,1.287813e+07,7.755355e+06
std,19754.64740,3.152437e+07,15.422874,21.755356,3249.403484,3.921834e+04,1864.128991,163.324159,504.892965,797.411073,...,12.270018,4.166799,7.979250e+05,2.102737e+05,9.002350e+05,7.842602e+05,2.185303e+07,1.275689e+07,2.692126e+07,1.983109e+07
min,0.00000,-1.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,80.00000,7.118000e+04,2.000000,1.000000,26.000000,0.000000e+00,6.000000,0.000000,6.000000,0.000000,...,1.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,80.00000,1.452333e+06,3.000000,4.000000,30.000000,1.640000e+02,20.000000,0.000000,8.666667,5.301991,...,2.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,80.00000,8.805237e+06,5.000000,5.000000,63.000000,1.160100e+04,34.000000,6.000000,32.000000,10.263203,...,4.000000,20.000000,1.878000e+03,0.000000e+00,1.878000e+03,1.862000e+03,8.239725e+06,0.000000e+00,8.253838e+06,7.422849e+06
max,65532.00000,1.199999e+08,1932.000000,2942.000000,183012.000000,5.172346e+06,11680.000000,1472.000000,3867.000000,6692.644993,...,1931.000000,52.000000,1.000000e+08,3.950000e+07,1.000000e+08,1.000000e+08,1.200000e+08,6.530000e+07,1.200000e+08,1.200000e+08

In [4]:
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       ' Label'],
      dtype='str')

In [5]:
df[" Label"].value_counts()

 Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [8]:
df.isnull().sum().sort_values(ascending=False).head(20)

Flow Bytes/s                   4
Flow Duration                  0
Destination Port               0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Total Fwd Packets              0
Fwd Packet Length Max          0
Fwd Packet Length Min          0
Fwd Packet Length Std          0
Fwd Packet Length Mean         0
Bwd Packet Length Max          0
Bwd Packet Length Min          0
Bwd Packet Length Mean         0
Bwd Packet Length Std          0
Flow Packets/s                 0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
dtype: int64

In [9]:
import numpy as np

np.isinf(df.select_dtypes(include=np.number)).sum()

Destination Port               0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
                              ..
Active Min                     0
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Length: 78, dtype: int64

In [10]:

df.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225740,61374,61,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225741,61378,72,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225742,61375,75,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225743,61323,48,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225744,61326,68,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [11]:
df.to_csv(
    "../data/processed/ddos_clean.csv",
    index=False
)